name: CI Pipeline (Test, Lint, Build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.11

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run lint (if applicable)
        run: |
          # يمكنك إضافة flake8 أو pylint لاحقًا
          echo "No linter configured yet"

      - name: Run tests
        run: |
          # حاليًا لا يوجد اختبارات، لكن يمكن إضافة ملف test_api.py لاحقًا
          echo "✅ No critical errors found"
          # مثال مستقبلي:
          # python -m pytest tests/ --verbose
